# Generated by Django 3.2.9 on 2021-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='matric_no',
            field=models.CharField(default='ab123cde', max_length=100),
        ),
    ]
