# Generated by Django 3.2.9 on 2021-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_register_matric_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='matric_no',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
