# Generated by Django 3.2.9 on 2021-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_register_matric_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='matric_no',
        ),
        migrations.AddField(
            model_name='register',
            name='matric_number',
            field=models.CharField(default='564g46ff', max_length=100),
        ),
    ]
