# Generated by Django 3.2.9 on 2021-11-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211111_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='matric_number',
            field=models.CharField(default='564g46ff', max_length=100, null=True),
        ),
    ]
