# Generated by Django 3.2.9 on 2021-11-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211111_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(default='john', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(default='thomas', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='matric_number',
            field=models.CharField(default='564g46ff', max_length=100),
        ),
    ]
