# Generated by Django 3.2.9 on 2021-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211111_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='anything@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(default='first_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(default='last_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='matric_number',
            field=models.CharField(default='abcd1234', max_length=100),
        ),
    ]
