# Generated by Django 3.2.9 on 2021-11-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20211112_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, default='anything@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, default='first_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, default='last_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='matric_number',
            field=models.CharField(blank=True, default='abcd1234', max_length=100),
        ),
    ]
