# Generated by Django 3.2.9 on 2021-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211112_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
